
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 01 11:09:26 GMT-03:00 2013
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PERMISSION = 4;
  public static final int OBLIGATION = 5;
  public static final int TRUE = 11;
  public static final int SEMI = 15;
  public static final int NEXT = 9;
  public static final int EXIST = 2;
  public static final int RECOVERY = 6;
  public static final int FORALL = 3;
  public static final int EOF = 0;
  public static final int ID = 16;
  public static final int error = 1;
  public static final int IMPLIES = 13;
  public static final int RPAREN = 8;
  public static final int UNTIL = 10;
  public static final int IMPLIESTEMP = 14;
  public static final int NEG = 12;
  public static final int LPAREN = 7;
}

