
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 03 15:03:10 GMT-03:00 2014
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AND = 22;
  public static final int FORALL = 3;
  public static final int NEG = 19;
  public static final int OR = 23;
  public static final int RPAREN = 13;
  public static final int SEMI = 24;
  public static final int SPECIFICATION = 9;
  public static final int TRUE = 17;
  public static final int IMPLIES = 20;
  public static final int FUTURE = 7;
  public static final int LPAREN = 12;
  public static final int ID = 25;
  public static final int PERMISSION = 4;
  public static final int WEAKUNTIL = 15;
  public static final int GLOBALLY = 6;
  public static final int COMMA = 10;
  public static final int EXIST = 2;
  public static final int OBLIGATION = 5;
  public static final int EOF = 0;
  public static final int FALSE = 18;
  public static final int error = 1;
  public static final int INTERFACE = 8;
  public static final int UNTIL = 16;
  public static final int NEXT = 14;
  public static final int INITIALSTATE = 11;
  public static final int EQUIVALENCE = 21;
}

