
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 13 13:58:28 GMT-03:00 2013
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AND = 9;
  public static final int FORALL = 13;
  public static final int NEG = 8;
  public static final int OR = 10;
  public static final int RPAREN = 3;
  public static final int SEMI = 4;
  public static final int TRUE = 5;
  public static final int FUTURE = 18;
  public static final int IMPLIES = 11;
  public static final int LPAREN = 2;
  public static final int ID = 7;
  public static final int PERMISSION = 14;
  public static final int GLOBALLY = 19;
  public static final int OBLIGATION = 15;
  public static final int EOF = 0;
  public static final int FALSE = 6;
  public static final int error = 1;
  public static final int EXISTS = 12;
  public static final int UNTIL = 17;
  public static final int NEXT = 16;
}

